# Generated by Django 4.2.5 on 2023-11-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts_of_computer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_Type', models.CharField(max_length=255)),
                ('ram_Capacity', models.CharField(max_length=255)),
                ('ram_Frequency', models.CharField(max_length=255)),
                ('channel_Type', models.CharField(max_length=255)),
                ('ram_Compatibility', models.CharField(max_length=255)),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_Model', models.CharField(max_length=255)),
                ('processor_Manufacturer', models.CharField(max_length=255)),
                ('processor_Socket_Type', models.CharField(max_length=255)),
                ('processor_Series', models.CharField(max_length=255)),
                ('core_Count', models.CharField(max_length=255)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='MouseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_Type', models.CharField(max_length=255)),
                ('tracking_Type', models.CharField(max_length=255)),
                ('button_Count', models.CharField(max_length=255)),
                ('usage_Type', models.CharField(max_length=255)),
                ('max_DPI', models.CharField(max_length=255)),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='MotherboardFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_Socket_Type', models.CharField(max_length=255)),
                ('ram_Type', models.CharField(max_length=255)),
                ('compatible_Processors', models.CharField(max_length=255)),
                ('motherboard_Size', models.CharField(max_length=255)),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_Size', models.CharField(max_length=255)),
                ('resolution', models.CharField(max_length=255)),
                ('refresh_Rate', models.CharField(max_length=255)),
                ('panel_Type', models.CharField(max_length=255)),
                ('response_Time', models.CharField(max_length=255)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='KeyboardFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_Type', models.CharField(max_length=255)),
                ('mechanical', models.BooleanField()),
                ('keyboard_Layout', models.CharField(max_length=255)),
                ('wrist_Support', models.BooleanField()),
                ('numpad', models.BooleanField()),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsCardFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_Manufacturer', models.CharField(max_length=255)),
                ('gpu_Model', models.CharField(max_length=255)),
                ('memory_Type', models.CharField(max_length=255)),
                ('gpu_Memory_Capacity', models.CharField(max_length=255)),
                ('graphics_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='CoolerFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatible_Sockets', models.CharField(max_length=255)),
                ('led', models.CharField(max_length=255)),
                ('radiator_Size', models.CharField(max_length=255)),
                ('fan_Count', models.IntegerField()),
                ('cooler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerCaseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_Type', models.CharField(max_length=255)),
                ('PSU', models.CharField(max_length=255)),
                ('PSU_Location', models.CharField(max_length=255)),
                ('transparent_Case', models.CharField(max_length=255)),
                ('type_C', models.CharField(max_length=255)),
                ('computer_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='CaseFanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooling_Type', models.CharField(max_length=255)),
                ('fan_Count', models.CharField(max_length=255)),
                ('led_Type', models.CharField(max_length=255)),
                ('power_Connector', models.CharField(max_length=255)),
                ('rpm', models.CharField(max_length=255)),
                ('case_Fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product')),
            ],
        ),
    ]
