# Generated by Django 4.2.5 on 2023-11-03 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts_of_computer_app', '0003_rename_case_fan_casefanfeature_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefanfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='computercasefeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='coolerfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='graphicscardfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='keyboardfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='monitorfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='motherboardfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='mousefeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='processorfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='ramfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parts_of_computer_app.product'),
        ),
    ]
