# Generated by Django 4.2.5 on 2023-11-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_of_computer_app', '0005_coolerfeature_cooling_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolerfeature',
            name='fan_Count',
            field=models.IntegerField(null=True),
        ),
    ]
