# Generated by Django 4.2.5 on 2023-12-13 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts_of_computer_app', '0006_alter_coolerfeature_fan_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefanfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CaseFanFeature', to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='computercasefeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ComputerCaseFeature', to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='coolerfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CoolerFeature', to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='graphicscardfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GraphicsCardFeature', to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='keyboardfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='KeyboardFeature', to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='monitorfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MonitorFeature', to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='motherboardfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MotherboardFeature', to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='mousefeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MouseFeature', to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='processorfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ProcessorFeature', to='parts_of_computer_app.product'),
        ),
        migrations.AlterField(
            model_name='ramfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='RamFeature', to='parts_of_computer_app.product'),
        ),
    ]
